sudo: false
language: python
cache: pip
matrix:
  include:
  - python: 3.7
    dist: xenial
  - python: 3.6
    dist: xenial
  - python: 3.5
    dist: xenial
env:
  global:
    - COVERALLS_PARALLEL=true
    - LOGGING=info
install:
  - pip install -r requirements.txt --upgrade
  - pip install wheel pytest pytest-cov codecov --upgrade
script:
  - make coverage
after_success:
  - codecov
